-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black-format
        language: python
    -   id: isort
        name: isort
        entry: test
        language: python
    -   id: mypy
        name: mypy
        entry: test
        language: python
    -   id: flake8
        name: flake8
        entry: test
        language: python
