repos:
-   repo: local
    hooks:
    -   id: black
        name: black formatting
        entry: black
        language: python
        args: ["--line-length=78"]
    -   id: isort
        name: check imports
        entry: isort
        language: python
    -   id: flake8
        name: file formatting
        entry: flake8
        language: python
        args: ["--max-line-length=78", "--ignore=E999,E501"]